apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
      annotations:
        checksum/config: "{{ .Values.configmap | toYaml | sha256sum }}"
    spec:
      containers:
        - name: influxdb
          image: influxdb:2.7.11
          ports:
            - containerPort: 8086
          env:
            - name: INFLUXDB_DB
              value: "smarthomedb"
            - name: INFLUXDB_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: INFLUXDB_ADMIN_USER
            - name: INFLUXDB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: INFLUXDB_ADMIN_PASSWORD
          volumeMounts:
            - name: influxdb-storage
              mountPath: /var/lib/influxdb2
      volumes:
        - name: influxdb-storage
          persistentVolumeClaim:
            claimName: influxdb-pvc