{
 "title": "Zisterne Füllstand",
 "tags": [
  "water",
  "cisterne",
  "zisterne"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Zisterne", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Aktueller Füllstand",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, value_percent AS \"Füllstand\" FROM percent_values WHERE measurement_id = 'Fuellstand_M1_Zisterne' ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Füllstand über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, value_percent AS \"Füllstand\" FROM percent_values WHERE $__timeFilter(time) AND measurement_id = 'Fuellstand_M1_Zisterne' ORDER BY time"
    }
   ]
  },
  {
   "title": "Letzte Messung",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTime:yyyy-MM-dd HH:mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time AS \"Letzte Aktualisierung\" FROM percent_values WHERE measurement_id = 'Fuellstand_M1_Zisterne' ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Alle Messpunkte (PunkteDiagramm)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, value_percent AS \"Füllstand\" FROM percent_values WHERE $__timeFilter(time) AND measurement_id = 'Fuellstand_M1_Zisterne' ORDER BY time"
    }
   ]
  }
 ]
}