apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: influxdb-storage
  nfs:
    path: /mnt/ssd
    server: smarthomepi2