###############################################
# Be sure to run kubectl create configmap telegraf-config --from-file=mqtt_import.conf
# before applying this deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: default
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf:latest
          env:
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influx-token-secret
                  key: INFLUX_TOKEN
            - name: TELEGRAF_CONFIG_PATH
              value: "/etc/telegraf/mqtt_import.conf"
          resources:
            limits:
              memory: 256Mi
              cpu: 200m
            requests:
              memory: 128Mi
              cpu: 100m
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf/mqtt_import.conf
              subPath: mqtt_import.conf
      volumes:
        - name: config
          configMap:
            name: telegraf-config
        - name: influx-token-volume
          secret:
            secretName: influx-token-secret