// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainScreen
extern void ui_mainScreen_screen_init(void);
extern void ui_mainScreen_screen_destroy(void);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_iconWifi;
extern lv_obj_t * ui_iconHeatpump;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_lblTempOutside;
extern lv_obj_t * ui_lblTime;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_btnLivingroom;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_lblBatteryLivingroom;
extern lv_obj_t * ui_lblCurrentTempLivingroom;
extern lv_obj_t * ui_lblTargetTempLivingroom;
extern lv_obj_t * ui_btnDiningroom;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_lblBatteryDiningroom;
extern lv_obj_t * ui_lblCurrentTempDiningroom;
extern lv_obj_t * ui_lblTargetTempDiningroom;
extern lv_obj_t * ui_btnKitchen;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_lblBatteryKitchen;
extern lv_obj_t * ui_lblCurrentTempKitchen;
extern lv_obj_t * ui_lblTargetTempKitchen;
extern lv_obj_t * ui_btnStudy;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_lblBatteryStudy;
extern lv_obj_t * ui_lblCurrentTempStudy;
extern lv_obj_t * ui_lblTargetTempStudy;
extern lv_obj_t * ui_btnGuestroom;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_lblBatteryGuestroom;
extern lv_obj_t * ui_lblCurrentTempGuestroom;
extern lv_obj_t * ui_lblTargetTempGuestroom;
extern lv_obj_t * ui_arcTargetTemp;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_lblValveOpen;
extern lv_obj_t * ui_lblTargetTemp;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_lblCurrentTemp;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_pnlTransferData;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_pgbTransferData;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

