apiVersion: apps/v1
kind: Deployment
metadata:
  name: shellyconnector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shellyconnector
  template:
    metadata:
      labels:
        app: shellyconnector
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet 
      containers:
        - name: shellyconnector
          image: tschissler/shellyconnector:latest
          env:
          # - name: EnvoyM3Serial
          #   value: "env:EnvoyM3Serial"
          # - name: EnphaseUserName
          #   value: "env:EnphaseUserName"
          # - name: EnphasePassword
          #   value: "env:EnphasePassword"
---
apiVersion: v1
kind: Service
metadata:
  name: shellyconnector-service
spec:
  type: ClusterIP    
  ports:  
  - name: udp-port
    port: 7090
    protocol: UDP
  selector:
    app: shellyconnector