apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmwconnector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmwconnector
  template:
    metadata:
      labels:
        app: bmwconnector
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet 
      containers:
        - name: bmwconnector
          image: tschissler/bmwconnector:latest
          volumeMounts:
          - name: token-volume
            mountPath: /etc/secrets
            readOnly: true
          env:
          - name: BMW_USERNAME
            value: "env:BMW_USERNAME"
          - name: BMW_PASSWORD
            value: "env:BMW_PASSWORD"
          - name: BMW_VIN
            value: "env:BMW_VIN"
      volumes:
        - name: token-volume
          secret:
            secretName: bmw-connect-api-token