namespace SharedContracts
{
    public record ChargingResult (
            int InsideChargingPowerWatts,
            int OutsideChargingPowerWatts,
            int InsideChargingCurrentmA,
            int OutsideChargingCurrentmA
        );

    public class ChargingSituation
    {
        /// <summary>
        /// When the control cycle that produced this picture ran (UTC). Mandatory field of
        /// every payload, see MQTT-Topic-Konvention.md — the topic is retained, so without it
        /// a consumer cannot tell a live value from one the broker replayed.
        /// </summary>
        public DateTimeOffset Zeitpunkt { get; set; }

        /// <summary>
        /// Is a car connected to the inside charging station and ready for charging
        /// </summary>
        public bool InsideConnected { get; set; }

        /// <summary>
        /// Is a car connected to the outside charging station and ready for charging
        /// </summary>
        public bool OutsideConnected { get; set; }

        /// <summary>
        /// The current power consumption of the house in Watts, wallboxes included. This is
        /// the Envoy channel PowerToHouse of M3 (see Program.cs, data/electricity/envoym3),
        /// the same quantity the DataHub writes to power_values as measurement "PowerToHouse"
        /// — only converted from milliwatts to Watts. The attribution rule of
        /// Docs/Ladeprotokoll.md names it V and uses it as its denominator.
        /// </summary>
        public int HouseConsumptionPower { get; set; }

        /// <summary>
        /// Current power consumption of the inside charging station in Watts
        /// </summary>
        public int InsideCurrentChargingPower { get; set; }

        /// <summary>
        /// Current power consumption of the outside charging station in Watts
        /// </summary>
        public int OutsideCurrentChargingPower { get; set; }

        /// <summary>
        /// Current power generated by the PV in Watts. The Enphase connector delivers
        /// milliwatts; Program.cs divides by 1000 when reading the value, so what is stored
        /// here is Watts, like every other power field of this class.
        /// </summary>
        public int PowerFromPV { get; set; }

        /// <summary>
        /// Current power used from the grid in Watts, negative when feeding into the grid.
        /// </summary>
        public int PowerFromGrid { get; set; }

        /// <summary>
        /// The power consumed from the battery in Watts, negative while the battery is charged.
        /// </summary>
        public int PowerFromBattery { get; set; }

        /// <summary>
        /// The current charge level of the battery in percent  
        /// </summary>
        public int BatteryLevel { get; set; }

        /// <summary>
        /// The power that should be used for charging the car inside in Watts
        /// </summary>
        public int InsideChargingLatestmA { get; set; }

        /// <summary>
        /// The power that should be used for charging the car outside in Watts
        /// </summary>
        public int OutsideChargingLatestmA { get; set; }

        /// <summary>
        /// The energy that has been charged in the current session in Wh
        /// </summary>
        public decimal InsideChargingCurrentSessionWh { get; set; }
        /// <summary>
        /// The energy that has been charged in the current session in Wh
        /// </summary>
        public decimal OutsideChargingCurrentSessionWh { get; set; }

        /// <summary>
        /// The surplus power in Watts the controller based its latest decision on
        /// (smoothed). Published for diagnostics.
        /// </summary>
        public int AvailableChargingPowerWatts { get; set; }

        /// <summary>
        /// Number of times the inside wallbox was switched on by the controller since
        /// the service started. Used to monitor the contactor load.
        /// </summary>
        public int InsideSwitchCycles { get; set; }

        /// <summary>
        /// Number of times the outside wallbox was switched on by the controller since
        /// the service started. Used to monitor the contactor load.
        /// </summary>
        public int OutsideSwitchCycles { get; set; }

        /// <summary>
        /// Hysteresis state for battery supported charging (ChargingLevel 3):
        /// switched off when the battery drops below the minimum level and only
        /// switched on again once the battery has recovered a few percent above it,
        /// so the charging does not oscillate around the minimum level.
        /// </summary>
        public bool BatterySupportedChargingActive { get; set; }

        public ChargingSituation()
        {
            InsideChargingLatestmA = -1;
            OutsideChargingLatestmA = -1;
            BatterySupportedChargingActive = true;
        }

        /// <summary>
        /// Shallow copy, used to hand filtered power readings to the decision logic
        /// while this instance keeps the raw values for publishing and for the next
        /// filter step.
        /// </summary>
        public ChargingSituation Clone() => (ChargingSituation)MemberwiseClone();
    }
}
