apiVersion: apps/v1
kind: Deployment
metadata:
  name: smarthomedatahub
  labels:
    app: smarthomedatahub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smarthomedatahub
  template:
    metadata:
      labels:
        app: smarthomedatahub
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet 
      containers:
        - name: smarthomedatahub
          image: tschissler/smarthomedatahub:latest
          env:
          - name: SMARTHOME__INFLUX3_URL
            value: "env:SMARTHOME_INFLUX3_URL"
          - name: SMARTHOME__INFLUXDB3_TOKEN
            value: "env:SMARTHOME__INFLUXDB3_TOKEN"
          - name: "SMARTHOME__DATAHUB_ENVIRONMENT"
            value: "env:SMARTHOME__DATAHUB_ENVIRONMENT"
          - name: SMARTHOME__INFLUXDB_ORG
            value: "env:SMARTHOME_INFLUXDB_ORG"
          - name: SMARTHOME__MQTT_BROKER
            value: "env:SMARTHOME__MQTT_BROKER"
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10          
---
apiVersion: v1
kind: Service
metadata:
  name: smarthomedatahub-service
  labels:
    app: smarthomedatahub
spec:
  type: ClusterIP    
  ports:  
  - name: udp-port
    port: 7090
    protocol: UDP
  selector:
    app: smarthomedatahub
