apiVersion: apps/v1
kind: Deployment
metadata:
  name: smarthomedatahub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smarthomedatahub
  template:
    metadata:
      labels:
        app: smarthomedatahub
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet 
      containers:
        - name: smarthomedatahub
          image: tschissler/smarthomedatahub:latest
          env:
          - name: INFLUX_TOKEN
            value: "env:INFLUX_TOKEN"
          - name: INFLUX_ORG
            value: "env:INFLUX_ORG"
          # - name: EnphaseUserName
          #   value: "env:EnphaseUserName"
          # - name: EnphasePassword
          #   value: "env:EnphasePassword"
---
apiVersion: v1
kind: Service
metadata:
  name: smarthomedatahub-service
spec:
  type: ClusterIP    
  ports:  
  - name: udp-port
    port: 7090
    protocol: UDP
  selector:
    app: smarthomedatahub