apiVersion: apps/v1
kind: Deployment
metadata:
  name: smarthomeweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smarthomeweb
  template:
    metadata:
      labels:
        app: smarthomeweb
    spec:
      containers:
        - name: smarthomeweb
          image: tschissler/smarthomeweb:latest
          ports:
            - containerPort: 8080
          env:
            - name: SyncfusionLicenseKey
              value: init