apiVersion: v1
kind: Service
metadata:
  name: mqttbroker-service
spec:
  selector:
    app: mqttbroker
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 32004
  type: NodePort