apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    app: grafana
data:
  influxdb-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: InfluxDB
        type: influxdb
        access: proxy
        url: http://smarthomepi2:32086
        isDefault: true
        version: 2
        jsonData:
          organization: smarthome
          defaultBucket: SmartHomeData
        secureJsonData:
          tokenFile: /etc/grafana/provisioning/datasources/secrets/token
