apiVersion: apps/v1
kind: Deployment
metadata:
  name: enphaseconnector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enphaseconnector
  template:
    metadata:
      labels:
        app: enphaseconnector
    spec:
      containers:
        - name: enphaseconnector
          image: tschissler/enphaseconnector:latest
          env:
          - name: EnvoyM1Serial
            value: "env:EnvoyM1Serial"
          - name: EnvoyM3Serial
            value: "env:EnvoyM3Serial"
          - name: EnphaseUserName
            value: "env:EnphaseUserName"
          - name: EnphasePassword
            value: "env:EnphasePassword"