apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mosquitto
spec:
  serviceName: mosquitto
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:latest
        ports:
          - containerPort: 1883
          - containerPort: 9001
        volumeMounts:
          - name: mosquitto-data
            mountPath: /mosquitto/data
          - name: mosquitto-config
            mountPath: /mosquitto/config
      volumes:
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: mosquitto-pvc
        - name: mosquitto-config
          configMap:
            name: mosquitto-config