apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageconnector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storageconnector
  template:
    metadata:
      labels:
        app: storageconnector
    spec:
      containers:
        - name: storageconnector
          image: tschissler/storageconnector:latest
          env:
          - name: SmartHomeStorageKey
            value: "env:SMARTHOMESTORAGEKEY"
          - name: SmartHomeStorageUri
            value: "env:SMARTHOMESTORAGEURI"