apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb3-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: influxdb3-storage
  volumeName: influxdb3-pv