name: LEDStripeFirmware CD

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/LEDStripeFirmware.yml
      - ESP32Firmwares/LEDStripe.Firmware/**
  
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      blob_url: ${{ steps.construct_blob_url.outputs.blob_url }}
    defaults:
      run:
        working-directory: ESP32Firmwares/LEDStripe.Firmware
  
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Build with PlatformIO  
      env:
        WIFI_SSID: ${{ secrets.WIFI_SSID }}
        WIFI_PASSWORD: ${{ secrets.WIFI_PASSWORD }}
      run: |
        pio run

    - name: Upload Firmware to Azure Blob Storage
      run: |
        az storage blob upload --account-name iotstoragem1 \
                               --container-name firmwareupdates \
                               --name firmware_${{ github.run_id }}.bin \
                               --file .pio/build/esp32dev/firmware.bin \
                               --account-key ${{ secrets.AZURE_STORAGE_KEY }}
                               
    - name: Construct Blob URL
      id: construct_blob_url
      run: echo "::set-output name=blob_url::https://iotstoragem1.blob.core.windows.net/firmwareupdates/firmware_${{ github.run_id }}.bin"
                           
  triggerupdate:
    needs: build
    runs-on: [self-hosted, linux]
    steps:
#    - name: Install Mosquitto Clients
#      run: sudo apt-get install -y mosquitto-clients

    - name: Trigger MQTT Update Message
      run: |
        mosquitto_pub -h smarthomepi2 -p 32004 -t OTAUpdateLEDStripeTopic -m ${{ needs.build.outputs.blob_url }}
