name: LEDStripeFirmware CD

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/LEDStripeFirmware.yml
      - ESP32Firmwares/LEDStripe.Firmware/**
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ESP32Firmwares/LEDStripe.Firmware
  
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Build with PlatformIO      
      run: |
        pio run

    - name: Upload Firmware to Azure Blob Storage
      run: |
        az storage blob upload --account-name iotstoragem1 \
                               --container-name firmwareupdates \
                               --name firmware_${{ github.run_id }}.elf \
                               --file .pio/build/esp32dev/firmware.elf \
                               --account-key ${{ secrets.AZURE_STORAGE_KEY }}
        env: 
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
