name: LEDStripeFirmware CD

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/LEDStripeFirmware.yml
      - ESP32Firmwares/LEDStripe.Firmware/**
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Build with PlatformIO
      run: |
        pio run
