name: Smarthome App CD

on:
    push:
      branches: [ "main" ]
      paths:
        - .github/workflows/Smarthome_app.yml
        - smarthome_app/**

env:
  PROJECT_NAME: smarthome_app
  
jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2.14.0
      with:
        channel: 'stable'

    - name: Recreate release-key.jks
      run: |
        echo "${{ secrets.ANDROID_RELEASE_KEYSTORE_BASE64 }}" | base64 -d > android/app/release-key.jks
      working-directory: ./${{ env.PROJECT_NAME }}

    - name: Install Dependencies
      run: flutter pub get
      working-directory: ./${{ env.PROJECT_NAME }}

    - name: Build AppBundle
      env:
        KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      run: |
        echo "storePassword=$KEYSTORE_PASSWORD" > android/key.properties
        echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
        echo "keyAlias=$KEY_ALIAS" >> android/key.properties
        echo "storeFile=release-key.jks" >> android/key.properties
        flutter build appbundle --release
      working-directory: ./${{ env.PROJECT_NAME }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: app-release.aab
        path: ./${{ env.PROJECT_NAME }}/build/app/outputs/bundle/release/app-release.aab

  deploy:
    name: Deploy to Google Play
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to Google Play
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
        packageName: "dev.tschissler.smarthome_app"
        releaseFiles: build/app/outputs/bundle/release/app-release.aab
        track: internal
