name: SmartHomeBlazorApp iOS CD

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/SmartHomeBlazorAppiOS.yml
      - SmartHome.Web/SmartHomeBlazorApp/**

env:
  PROJECT_NAME: SmartHomeBlazorApp
  CONFIGURATION: Release
  DOTNET_VERSION: 8.0.x
  XCODE_VERSION: 15.1
  WORKING_DIRECTORY: SmartHome.Web/SmartHomeBlazorApp
  APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.IOSAPPSTORE_PRIVATE_KEY }}
  
jobs:
  build-and-deploy:
    #runs-on: [self-hosted, macOS] 
    runs-on: macos-13

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2 

    - name: Ensure using the right XCode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}

    - name: Import Code-Signing Certificates
      uses: Apple-Actions/import-codesign-certs@253ddeeac23f2bdad1646faac5c8c2832e800071
      with:
        # The path to the PKCS12 file to import.
        p12-filepath: ${{ env.WORKING_DIRECTORY }}/Platforms/iOS/DistributionCertificates.p12
        # The password used to import the PKCS12 file.
        p12-password: ${{ secrets.IOS_CERTIFICATE_PASSPHRASE }}

    - name: Apple Provisioning Profiles Downloader
      uses: poad/apple-provisioning-profiles-downloader@v1.0.8
      with:
        # The bundle identifier of the application
        bundle-id: 'de.agilemax.smarthome.blazor.ios'
        # The type of profile to download. One of IOS_APP_DEVELOPMENT, IOS_APP_STORE, IOS_APP_ADHOC, IOS_APP_INHOUSE, MAC_APP_DEVELOPMENT, MAC_APP_STORE, MAC_APP_DIRECT, TVOS_APP_DEVELOPMENT, TVOS_APP_STORE, TVOS_APP_ADHOC, TVOS_APP_INHOUSE
        profile-type: IOS_APP_STORE
        # The AppStore Connect API Key Issuer Identifier
        issuer-id: ${{ secrets.IOSAPPSTORE_ISSUER_ID }}
        # The Key ID for AppStore Connect API
        api-key-id: ${{ secrets.IOSAPPSTORE_KEY_ID }}
        # The PKCS8 format Private Key for AppStore Connect API
        #api-private-key: "${{ env.WORKING_DIRECTORY }}/Platforms/iOS/AuthKey_G3XADS6382.p8"
        # The PKCS8 format Private Key file for AppStore Connect API
        api-private-key-file: ${{ github.workspace}}/${{ env.WORKING_DIRECTORY }}/Platforms/iOS/AuthKey_X9N93NF8L3.p8
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install MAUI workload
      run: dotnet workload install maui
      
    - name: Restore NuGet Packages
      run: dotnet restore  "${{ env.WORKING_DIRECTORY }}"

    - name: Build .NET MAUI iOS Project
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} 

    - name: Publish .NET MAUI iOS Project
      #run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore -f net8.0-ios
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" -f net8.0-ios -p:ArchiveOnBuild=true 

    - name: Debug
      run: ls "${{ env.WORKING_DIRECTORY }}/bin/Release/net8.0-ios/ios-arm64/publish/"
      
    #- name: Download Apple Provisioning Profiles
    #  uses: Apple-Actions/download-provisioning-profiles@v1
    #  with:
    #    bundle-id: 'com.agilemax.App.SmartHome.Blazor'
    #    issuer-id: ${{ secrets.IOSAPPSTORE_ISSUER_ID }}
    #    api-key-id: ${{ secrets.IOSAPPSTORE_KEY_ID }}
    #    api-private-key: ${{ secrets.IOSAPPSTORE_PRIVATE_KEY }}
    #    profile-type: 
    #- name: Install Fastlane
    #  run: |  # Install Fastlane for app signing and uploading
    #    sudo gem install fastlane


    #- name: Build and Sign IPA
    #  run: fastlane gym --scheme "YourScheme" --export_method "app-store"  # Replace "YourScheme" with your project's scheme

    - name: Upload to TestFlight
      uses: Apple-Actions/upload-testflight-build@v1
      with:
        app-path: ${{ env.WORKING_DIRECTORY }}/bin/Release/net8.0-ios/ios-arm64/publish/SmartHomeBlazorApp.ipa  # Path to your IPA file
        app-type: ios
        issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        api-key-id: ${{ secrets.IOSAPPSTORE_KEY_ID }}
    #    key-id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
    #    private-key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
    #    app-id: "com.example.app"  # Replace with your app's bundle identifier

    - name: Complete Deployment
      run: echo "Deployment to App Store Connect complete"
