name: SmartHomeBlazorApp iOS CD

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/SmartHomeBlazorAppiOS.yml
      - SmartHome.Web/SmartHomeBlazorApp/**

env:
  PROJECT_NAME: SmartHomeBlazorApp
  CONFIGURATION: Release
  DOTNET_VERSION: 8.0.x
  XCODE_VERSION: 15.1
  WORKING_DIRECTORY: SmartHome.Web/SmartHomeBlazorApp
  
jobs:
  build-and-deploy:
    runs-on: macos-latest 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2 

    - name: Ensure using the right XCode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install MAUI workload
      run: dotnet workload install maui
      
    - name: Restore NuGet Packages
      run: dotnet restore  "${{ env.WORKING_DIRECTORY }}"

    - name: Build .NET MAUI iOS Project
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
      #run: dotnet build SmartHome.Web/SmartHomeBlazorApp/SmartHomeBlazorApp.csproj -c Release -f net8.0-ios  # Build your .NET MAUI iOS project

    #- name: Install Fastlane
    #  run: |  # Install Fastlane for app signing and uploading
    #    sudo gem install fastlane

    #- name: Import Certificates
    #  uses: apple-actions/import-codesign-certs@v1
    #  with:
    #    p12-file-base64: ${{ secrets.P12_FILE_BASE64 }}  # Encoded .p12 file
    #    p12-password: ${{ secrets.P12_PASSWORD }}  # Password for the .p12 file

    #- name: Build and Sign IPA
    #  run: fastlane gym --scheme "YourScheme" --export_method "app-store"  # Replace "YourScheme" with your project's scheme

    #- name: Upload to App Store Connect
    #  uses: apple-actions/upload-app-store@v1
    #  with:
    #    app-path: ./path/to/your/app.ipa  # Path to your IPA file
    #    issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
    #    key-id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
    #    private-key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
    #    app-id: "com.example.app"  # Replace with your app's bundle identifier

    #- name: Complete Deployment
    #  run: echo "Deployment to App Store Connect complete"
