name: StorageConnector CD

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/StorageConnector.yml
      - StorageConnector/**

env:
  PROJECT_NAME: StorageConnector
  IMAGE_NAME: storageconnector
  
jobs:

  build:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v3

    - name: Build and publish Docker image
      run: |        
        # Build the Docker image with the package version tag.
        docker build \
            -t tschissler/${{ env.IMAGE_NAME }}:${{ github.run_id }} \
            -t tschissler/${{ env.IMAGE_NAME }}:latest \
            -f ./${{ env.PROJECT_NAME }}/Dockerfile \
            --push .

    - name: Update Kubernetes deployment
      run: |
        microk8s kubectl set image deployments/${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}=tschissler/${{ env.IMAGE_NAME }}:${{ github.run_id }}
        microk8s kubectl set env deployment/storageconnector SmartHomeStorageUri="${{ secrets.SMARTHOMESTORAGEURI }}"
        microk8s kubectl set env deployment/storageconnector SmartHomeStorageKey="${{ secrets.SMARTHOMESTORAGEKEY }}"
